import { createAccessControl } from 'better-auth/plugins/access';
import { defaultStatements as defaultAdminStatement } from 'better-auth/plugins/admin/access';

const statement = {
  users: ['create', 'read', 'list', 'update', 'delete'],
  user: ['create', 'read', 'update', 'delete', 'list'],
  products: ['create', 'read', 'update', 'delete'],
  categories: ['create', 'read', 'update', 'delete'],
  transaction: ['create', 'read', 'update', 'delete', 'refund'],
  outlets: ['create', 'read', 'update', 'delete'],
  tenants: ['create', 'read', 'update', 'delete'],
  stocks: ['create', 'read', 'update', 'delete'],
  stockAdjustments: ['create', 'read', 'update', 'delete'],
  orders: ['create', 'read', 'update', 'delete'],
  orderItems: ['create', 'read', 'update', 'delete'],
  report: ['read', 'export'],
  settings: ['read', 'update'],
  taxes: ['create', 'read', 'update', 'delete'],
  discounts: ['create', 'read', 'update', 'delete'],
  paymentMethods: ['create', 'read', 'update', 'delete'],
  cashShifts: ['create', 'read', 'update', 'delete'],
  dashboard: ['read'],
} as const;

export const ac = createAccessControl(statement);

export const adminRole = ac.newRole({
  ...defaultAdminStatement,
  users: ['create', 'read', 'list', 'update', 'delete'],
  user: ['create', 'read', 'update', 'delete', 'list'],
  products: ['create', 'read', 'update', 'delete'],
  categories: ['create', 'read', 'update', 'delete'],
  transaction: ['create', 'read', 'update', 'delete', 'refund'],
  outlets: ['create', 'read', 'update', 'delete'],
  report: ['read', 'export'],
  settings: ['read', 'update'],
  tenants: ['create', 'read', 'update', 'delete'],
  stocks: ['create', 'read', 'update', 'delete'],
  stockAdjustments: ['create', 'read', 'update', 'delete'],
  orders: ['create', 'read', 'update', 'delete'],
  orderItems: ['create', 'read', 'update', 'delete'],
  taxes: ['create', 'read', 'update', 'delete'],
  discounts: ['create', 'read', 'update', 'delete'],
  paymentMethods: ['create', 'read', 'update', 'delete'],
  cashShifts: ['create', 'read', 'update', 'delete'],
  dashboard: ['read'],
});

export const ownerRole = ac.newRole({
  users: ['create', 'read', 'list'],
  user: ['create', 'read', 'list'],
  products: ['create', 'read', 'update', 'delete'],
  categories: ['create', 'read', 'update', 'delete'],
  transaction: ['create', 'read', 'update', 'delete', 'refund'],
  outlets: ['create', 'read', 'update', 'delete'],
  report: ['read', 'export'],
  settings: ['read', 'update'],
  tenants: ['create', 'read', 'update'],
  stocks: ['create', 'read', 'update', 'delete'],
  stockAdjustments: ['create', 'read', 'update', 'delete'],
  orders: ['create', 'read', 'update', 'delete'],
  orderItems: ['create', 'read', 'update', 'delete'],
  taxes: ['create', 'read', 'update', 'delete'],
  discounts: ['create', 'read', 'update', 'delete'],
  paymentMethods: ['create', 'read', 'update', 'delete'],
  cashShifts: ['create', 'read', 'update', 'delete'],
  dashboard: ['read'],
});

export const cashierRole = ac.newRole({
  users: ['read'],
  user: ['read'],
  products: ['read'],
  categories: ['read'],
  transaction: ['create', 'read', 'refund'],
  outlets: ['read'],
  report: ['read'],
  settings: ['read'],
  tenants: ['read'],
  stocks: ['read'],
  stockAdjustments: ['read', 'create', 'update', 'delete'],
  orders: ['create', 'read'],
  orderItems: ['create', 'read'],
  taxes: ['read', 'update'],
  discounts: ['read', 'update'],
  paymentMethods: ['read'],
  cashShifts: ['create', 'read', 'update'],
  dashboard: ['read'],
});
