steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'VITE_API_URL=https://backend-pos-508482854424.us-central1.run.app/api'
      - '--build-arg'
      - 'VITE_APP_URL=https://frontend-pos-508482854424.us-central1.run.app'
      - '--tag'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_IMAGE_NAME}:${COMMIT_SHA}'
      - '--tag'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_IMAGE_NAME}:latest'
      - '.'
    dir: 'frontend-pos'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_IMAGE_NAME}:${COMMIT_SHA}'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_IMAGE_NAME}:latest'

substitutions:
  _REGION: us-central1
  _PROJECT_ID: dulcet-outlook-479500-k3
  _IMAGE_NAME: frontend-pos

images:
  - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_IMAGE_NAME}:${COMMIT_SHA}'
  - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_IMAGE_NAME}:latest'
