services:
  postgres-test:
    image: postgres:15-alpine
    container_name: pos-postgres-test
    environment:
      POSTGRES_USER: pos_user
      POSTGRES_PASSWORD: pos_password
      POSTGRES_DB: pos_database_test
    ports:
      - '5436:5432'
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U pos_user -d pos_database_test']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_test_data:
