/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as R403RouteImport } from './routes/403'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedtenantLaporanRouteImport } from './routes/_protected/(tenant)/laporan'
import { Route as ProtectedtenantDashboardRouteImport } from './routes/_protected/(tenant)/dashboard'
import { Route as ProtectedtenantUsersIndexRouteImport } from './routes/_protected/(tenant)/users/index'
import { Route as ProtectedtenantStocksIndexRouteImport } from './routes/_protected/(tenant)/stocks/index'
import { Route as ProtectedtenantStockAdjustmentIndexRouteImport } from './routes/_protected/(tenant)/stock-adjustment/index'
import { Route as ProtectedtenantSettingsIndexRouteImport } from './routes/_protected/(tenant)/settings/index'
import { Route as ProtectedtenantProductsIndexRouteImport } from './routes/_protected/(tenant)/products/index'
import { Route as ProtectedtenantPosIndexRouteImport } from './routes/_protected/(tenant)/pos/index'
import { Route as ProtectedtenantPaymentMethodsIndexRouteImport } from './routes/_protected/(tenant)/payment-methods/index'
import { Route as ProtectedtenantOutletsIndexRouteImport } from './routes/_protected/(tenant)/outlets/index'
import { Route as ProtectedtenantOrdersIndexRouteImport } from './routes/_protected/(tenant)/orders/index'
import { Route as ProtectedtenantDiscountsIndexRouteImport } from './routes/_protected/(tenant)/discounts/index'
import { Route as ProtectedtenantCategoriesIndexRouteImport } from './routes/_protected/(tenant)/categories/index'
import { Route as ProtectedtenantCashShiftsIndexRouteImport } from './routes/_protected/(tenant)/cash-shifts/index'
import { Route as ProtectedtenantAccountIndexRouteImport } from './routes/_protected/(tenant)/account/index'
import { Route as ProtectedglobalAllUsersIndexRouteImport } from './routes/_protected/(global)/all-users/index'
import { Route as ProtectedglobalAdminIndexRouteImport } from './routes/_protected/(global)/admin/index'
import { Route as ProtectedtenantProductsNewRouteImport } from './routes/_protected/(tenant)/products/new'
import { Route as ProtectedtenantProductsProductIdRouteImport } from './routes/_protected/(tenant)/products/$productId'
import { Route as ProtectedtenantOutletsOutletIdRouteImport } from './routes/_protected/(tenant)/outlets/$outletId'
import { Route as ProtectedtenantOrdersOrderIdRouteImport } from './routes/_protected/(tenant)/orders/$orderId'
import { Route as ProtectedtenantCategoriesCategoryIdRouteImport } from './routes/_protected/(tenant)/categories/$categoryId'
import { Route as ProtectedtenantCashShiftsCashShiftIdRouteImport } from './routes/_protected/(tenant)/cash-shifts/$cashShiftId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedtenantLaporanRoute = ProtectedtenantLaporanRouteImport.update({
  id: '/(tenant)/laporan',
  path: '/laporan',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedtenantDashboardRoute =
  ProtectedtenantDashboardRouteImport.update({
    id: '/(tenant)/dashboard',
    path: '/dashboard',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedtenantUsersIndexRoute =
  ProtectedtenantUsersIndexRouteImport.update({
    id: '/(tenant)/users/',
    path: '/users/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedtenantStocksIndexRoute =
  ProtectedtenantStocksIndexRouteImport.update({
    id: '/(tenant)/stocks/',
    path: '/stocks/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedtenantStockAdjustmentIndexRoute =
  ProtectedtenantStockAdjustmentIndexRouteImport.update({
    id: '/(tenant)/stock-adjustment/',
    path: '/stock-adjustment/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedtenantSettingsIndexRoute =
  ProtectedtenantSettingsIndexRouteImport.update({
    id: '/(tenant)/settings/',
    path: '/settings/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedtenantProductsIndexRoute =
  ProtectedtenantProductsIndexRouteImport.update({
    id: '/(tenant)/products/',
    path: '/products/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedtenantPosIndexRoute = ProtectedtenantPosIndexRouteImport.update({
  id: '/(tenant)/pos/',
  path: '/pos/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedtenantPaymentMethodsIndexRoute =
  ProtectedtenantPaymentMethodsIndexRouteImport.update({
    id: '/(tenant)/payment-methods/',
    path: '/payment-methods/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedtenantOutletsIndexRoute =
  ProtectedtenantOutletsIndexRouteImport.update({
    id: '/(tenant)/outlets/',
    path: '/outlets/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedtenantOrdersIndexRoute =
  ProtectedtenantOrdersIndexRouteImport.update({
    id: '/(tenant)/orders/',
    path: '/orders/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedtenantDiscountsIndexRoute =
  ProtectedtenantDiscountsIndexRouteImport.update({
    id: '/(tenant)/discounts/',
    path: '/discounts/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedtenantCategoriesIndexRoute =
  ProtectedtenantCategoriesIndexRouteImport.update({
    id: '/(tenant)/categories/',
    path: '/categories/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedtenantCashShiftsIndexRoute =
  ProtectedtenantCashShiftsIndexRouteImport.update({
    id: '/(tenant)/cash-shifts/',
    path: '/cash-shifts/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedtenantAccountIndexRoute =
  ProtectedtenantAccountIndexRouteImport.update({
    id: '/(tenant)/account/',
    path: '/account/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedglobalAllUsersIndexRoute =
  ProtectedglobalAllUsersIndexRouteImport.update({
    id: '/(global)/all-users/',
    path: '/all-users/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedglobalAdminIndexRoute =
  ProtectedglobalAdminIndexRouteImport.update({
    id: '/(global)/admin/',
    path: '/admin/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedtenantProductsNewRoute =
  ProtectedtenantProductsNewRouteImport.update({
    id: '/(tenant)/products/new',
    path: '/products/new',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedtenantProductsProductIdRoute =
  ProtectedtenantProductsProductIdRouteImport.update({
    id: '/(tenant)/products/$productId',
    path: '/products/$productId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedtenantOutletsOutletIdRoute =
  ProtectedtenantOutletsOutletIdRouteImport.update({
    id: '/(tenant)/outlets/$outletId',
    path: '/outlets/$outletId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedtenantOrdersOrderIdRoute =
  ProtectedtenantOrdersOrderIdRouteImport.update({
    id: '/(tenant)/orders/$orderId',
    path: '/orders/$orderId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedtenantCategoriesCategoryIdRoute =
  ProtectedtenantCategoriesCategoryIdRouteImport.update({
    id: '/(tenant)/categories/$categoryId',
    path: '/categories/$categoryId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedtenantCashShiftsCashShiftIdRoute =
  ProtectedtenantCashShiftsCashShiftIdRouteImport.update({
    id: '/(tenant)/cash-shifts/$cashShiftId',
    path: '/cash-shifts/$cashShiftId',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard': typeof ProtectedtenantDashboardRoute
  '/laporan': typeof ProtectedtenantLaporanRoute
  '/cash-shifts/$cashShiftId': typeof ProtectedtenantCashShiftsCashShiftIdRoute
  '/categories/$categoryId': typeof ProtectedtenantCategoriesCategoryIdRoute
  '/orders/$orderId': typeof ProtectedtenantOrdersOrderIdRoute
  '/outlets/$outletId': typeof ProtectedtenantOutletsOutletIdRoute
  '/products/$productId': typeof ProtectedtenantProductsProductIdRoute
  '/products/new': typeof ProtectedtenantProductsNewRoute
  '/admin/': typeof ProtectedglobalAdminIndexRoute
  '/all-users/': typeof ProtectedglobalAllUsersIndexRoute
  '/account/': typeof ProtectedtenantAccountIndexRoute
  '/cash-shifts/': typeof ProtectedtenantCashShiftsIndexRoute
  '/categories/': typeof ProtectedtenantCategoriesIndexRoute
  '/discounts/': typeof ProtectedtenantDiscountsIndexRoute
  '/orders/': typeof ProtectedtenantOrdersIndexRoute
  '/outlets/': typeof ProtectedtenantOutletsIndexRoute
  '/payment-methods/': typeof ProtectedtenantPaymentMethodsIndexRoute
  '/pos/': typeof ProtectedtenantPosIndexRoute
  '/products/': typeof ProtectedtenantProductsIndexRoute
  '/settings/': typeof ProtectedtenantSettingsIndexRoute
  '/stock-adjustment/': typeof ProtectedtenantStockAdjustmentIndexRoute
  '/stocks/': typeof ProtectedtenantStocksIndexRoute
  '/users/': typeof ProtectedtenantUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard': typeof ProtectedtenantDashboardRoute
  '/laporan': typeof ProtectedtenantLaporanRoute
  '/cash-shifts/$cashShiftId': typeof ProtectedtenantCashShiftsCashShiftIdRoute
  '/categories/$categoryId': typeof ProtectedtenantCategoriesCategoryIdRoute
  '/orders/$orderId': typeof ProtectedtenantOrdersOrderIdRoute
  '/outlets/$outletId': typeof ProtectedtenantOutletsOutletIdRoute
  '/products/$productId': typeof ProtectedtenantProductsProductIdRoute
  '/products/new': typeof ProtectedtenantProductsNewRoute
  '/admin': typeof ProtectedglobalAdminIndexRoute
  '/all-users': typeof ProtectedglobalAllUsersIndexRoute
  '/account': typeof ProtectedtenantAccountIndexRoute
  '/cash-shifts': typeof ProtectedtenantCashShiftsIndexRoute
  '/categories': typeof ProtectedtenantCategoriesIndexRoute
  '/discounts': typeof ProtectedtenantDiscountsIndexRoute
  '/orders': typeof ProtectedtenantOrdersIndexRoute
  '/outlets': typeof ProtectedtenantOutletsIndexRoute
  '/payment-methods': typeof ProtectedtenantPaymentMethodsIndexRoute
  '/pos': typeof ProtectedtenantPosIndexRoute
  '/products': typeof ProtectedtenantProductsIndexRoute
  '/settings': typeof ProtectedtenantSettingsIndexRoute
  '/stock-adjustment': typeof ProtectedtenantStockAdjustmentIndexRoute
  '/stocks': typeof ProtectedtenantStocksIndexRoute
  '/users': typeof ProtectedtenantUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/_protected': typeof ProtectedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_protected/(tenant)/dashboard': typeof ProtectedtenantDashboardRoute
  '/_protected/(tenant)/laporan': typeof ProtectedtenantLaporanRoute
  '/_protected/(tenant)/cash-shifts/$cashShiftId': typeof ProtectedtenantCashShiftsCashShiftIdRoute
  '/_protected/(tenant)/categories/$categoryId': typeof ProtectedtenantCategoriesCategoryIdRoute
  '/_protected/(tenant)/orders/$orderId': typeof ProtectedtenantOrdersOrderIdRoute
  '/_protected/(tenant)/outlets/$outletId': typeof ProtectedtenantOutletsOutletIdRoute
  '/_protected/(tenant)/products/$productId': typeof ProtectedtenantProductsProductIdRoute
  '/_protected/(tenant)/products/new': typeof ProtectedtenantProductsNewRoute
  '/_protected/(global)/admin/': typeof ProtectedglobalAdminIndexRoute
  '/_protected/(global)/all-users/': typeof ProtectedglobalAllUsersIndexRoute
  '/_protected/(tenant)/account/': typeof ProtectedtenantAccountIndexRoute
  '/_protected/(tenant)/cash-shifts/': typeof ProtectedtenantCashShiftsIndexRoute
  '/_protected/(tenant)/categories/': typeof ProtectedtenantCategoriesIndexRoute
  '/_protected/(tenant)/discounts/': typeof ProtectedtenantDiscountsIndexRoute
  '/_protected/(tenant)/orders/': typeof ProtectedtenantOrdersIndexRoute
  '/_protected/(tenant)/outlets/': typeof ProtectedtenantOutletsIndexRoute
  '/_protected/(tenant)/payment-methods/': typeof ProtectedtenantPaymentMethodsIndexRoute
  '/_protected/(tenant)/pos/': typeof ProtectedtenantPosIndexRoute
  '/_protected/(tenant)/products/': typeof ProtectedtenantProductsIndexRoute
  '/_protected/(tenant)/settings/': typeof ProtectedtenantSettingsIndexRoute
  '/_protected/(tenant)/stock-adjustment/': typeof ProtectedtenantStockAdjustmentIndexRoute
  '/_protected/(tenant)/stocks/': typeof ProtectedtenantStocksIndexRoute
  '/_protected/(tenant)/users/': typeof ProtectedtenantUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/403'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/dashboard'
    | '/laporan'
    | '/cash-shifts/$cashShiftId'
    | '/categories/$categoryId'
    | '/orders/$orderId'
    | '/outlets/$outletId'
    | '/products/$productId'
    | '/products/new'
    | '/admin/'
    | '/all-users/'
    | '/account/'
    | '/cash-shifts/'
    | '/categories/'
    | '/discounts/'
    | '/orders/'
    | '/outlets/'
    | '/payment-methods/'
    | '/pos/'
    | '/products/'
    | '/settings/'
    | '/stock-adjustment/'
    | '/stocks/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/403'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/dashboard'
    | '/laporan'
    | '/cash-shifts/$cashShiftId'
    | '/categories/$categoryId'
    | '/orders/$orderId'
    | '/outlets/$outletId'
    | '/products/$productId'
    | '/products/new'
    | '/admin'
    | '/all-users'
    | '/account'
    | '/cash-shifts'
    | '/categories'
    | '/discounts'
    | '/orders'
    | '/outlets'
    | '/payment-methods'
    | '/pos'
    | '/products'
    | '/settings'
    | '/stock-adjustment'
    | '/stocks'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/403'
    | '/_protected'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/_protected/(tenant)/dashboard'
    | '/_protected/(tenant)/laporan'
    | '/_protected/(tenant)/cash-shifts/$cashShiftId'
    | '/_protected/(tenant)/categories/$categoryId'
    | '/_protected/(tenant)/orders/$orderId'
    | '/_protected/(tenant)/outlets/$outletId'
    | '/_protected/(tenant)/products/$productId'
    | '/_protected/(tenant)/products/new'
    | '/_protected/(global)/admin/'
    | '/_protected/(global)/all-users/'
    | '/_protected/(tenant)/account/'
    | '/_protected/(tenant)/cash-shifts/'
    | '/_protected/(tenant)/categories/'
    | '/_protected/(tenant)/discounts/'
    | '/_protected/(tenant)/orders/'
    | '/_protected/(tenant)/outlets/'
    | '/_protected/(tenant)/payment-methods/'
    | '/_protected/(tenant)/pos/'
    | '/_protected/(tenant)/products/'
    | '/_protected/(tenant)/settings/'
    | '/_protected/(tenant)/stock-adjustment/'
    | '/_protected/(tenant)/stocks/'
    | '/_protected/(tenant)/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R403Route: typeof R403Route
  ProtectedRoute: typeof ProtectedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/(tenant)/laporan': {
      id: '/_protected/(tenant)/laporan'
      path: '/laporan'
      fullPath: '/laporan'
      preLoaderRoute: typeof ProtectedtenantLaporanRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/(tenant)/dashboard': {
      id: '/_protected/(tenant)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedtenantDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/(tenant)/users/': {
      id: '/_protected/(tenant)/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof ProtectedtenantUsersIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/(tenant)/stocks/': {
      id: '/_protected/(tenant)/stocks/'
      path: '/stocks'
      fullPath: '/stocks/'
      preLoaderRoute: typeof ProtectedtenantStocksIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/(tenant)/stock-adjustment/': {
      id: '/_protected/(tenant)/stock-adjustment/'
      path: '/stock-adjustment'
      fullPath: '/stock-adjustment/'
      preLoaderRoute: typeof ProtectedtenantStockAdjustmentIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/(tenant)/settings/': {
      id: '/_protected/(tenant)/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof ProtectedtenantSettingsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/(tenant)/products/': {
      id: '/_protected/(tenant)/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProtectedtenantProductsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/(tenant)/pos/': {
      id: '/_protected/(tenant)/pos/'
      path: '/pos'
      fullPath: '/pos/'
      preLoaderRoute: typeof ProtectedtenantPosIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/(tenant)/payment-methods/': {
      id: '/_protected/(tenant)/payment-methods/'
      path: '/payment-methods'
      fullPath: '/payment-methods/'
      preLoaderRoute: typeof ProtectedtenantPaymentMethodsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/(tenant)/outlets/': {
      id: '/_protected/(tenant)/outlets/'
      path: '/outlets'
      fullPath: '/outlets/'
      preLoaderRoute: typeof ProtectedtenantOutletsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/(tenant)/orders/': {
      id: '/_protected/(tenant)/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof ProtectedtenantOrdersIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/(tenant)/discounts/': {
      id: '/_protected/(tenant)/discounts/'
      path: '/discounts'
      fullPath: '/discounts/'
      preLoaderRoute: typeof ProtectedtenantDiscountsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/(tenant)/categories/': {
      id: '/_protected/(tenant)/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof ProtectedtenantCategoriesIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/(tenant)/cash-shifts/': {
      id: '/_protected/(tenant)/cash-shifts/'
      path: '/cash-shifts'
      fullPath: '/cash-shifts/'
      preLoaderRoute: typeof ProtectedtenantCashShiftsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/(tenant)/account/': {
      id: '/_protected/(tenant)/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof ProtectedtenantAccountIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/(global)/all-users/': {
      id: '/_protected/(global)/all-users/'
      path: '/all-users'
      fullPath: '/all-users/'
      preLoaderRoute: typeof ProtectedglobalAllUsersIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/(global)/admin/': {
      id: '/_protected/(global)/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof ProtectedglobalAdminIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/(tenant)/products/new': {
      id: '/_protected/(tenant)/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof ProtectedtenantProductsNewRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/(tenant)/products/$productId': {
      id: '/_protected/(tenant)/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProtectedtenantProductsProductIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/(tenant)/outlets/$outletId': {
      id: '/_protected/(tenant)/outlets/$outletId'
      path: '/outlets/$outletId'
      fullPath: '/outlets/$outletId'
      preLoaderRoute: typeof ProtectedtenantOutletsOutletIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/(tenant)/orders/$orderId': {
      id: '/_protected/(tenant)/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof ProtectedtenantOrdersOrderIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/(tenant)/categories/$categoryId': {
      id: '/_protected/(tenant)/categories/$categoryId'
      path: '/categories/$categoryId'
      fullPath: '/categories/$categoryId'
      preLoaderRoute: typeof ProtectedtenantCategoriesCategoryIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/(tenant)/cash-shifts/$cashShiftId': {
      id: '/_protected/(tenant)/cash-shifts/$cashShiftId'
      path: '/cash-shifts/$cashShiftId'
      fullPath: '/cash-shifts/$cashShiftId'
      preLoaderRoute: typeof ProtectedtenantCashShiftsCashShiftIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedtenantDashboardRoute: typeof ProtectedtenantDashboardRoute
  ProtectedtenantLaporanRoute: typeof ProtectedtenantLaporanRoute
  ProtectedtenantCashShiftsCashShiftIdRoute: typeof ProtectedtenantCashShiftsCashShiftIdRoute
  ProtectedtenantCategoriesCategoryIdRoute: typeof ProtectedtenantCategoriesCategoryIdRoute
  ProtectedtenantOrdersOrderIdRoute: typeof ProtectedtenantOrdersOrderIdRoute
  ProtectedtenantOutletsOutletIdRoute: typeof ProtectedtenantOutletsOutletIdRoute
  ProtectedtenantProductsProductIdRoute: typeof ProtectedtenantProductsProductIdRoute
  ProtectedtenantProductsNewRoute: typeof ProtectedtenantProductsNewRoute
  ProtectedglobalAdminIndexRoute: typeof ProtectedglobalAdminIndexRoute
  ProtectedglobalAllUsersIndexRoute: typeof ProtectedglobalAllUsersIndexRoute
  ProtectedtenantAccountIndexRoute: typeof ProtectedtenantAccountIndexRoute
  ProtectedtenantCashShiftsIndexRoute: typeof ProtectedtenantCashShiftsIndexRoute
  ProtectedtenantCategoriesIndexRoute: typeof ProtectedtenantCategoriesIndexRoute
  ProtectedtenantDiscountsIndexRoute: typeof ProtectedtenantDiscountsIndexRoute
  ProtectedtenantOrdersIndexRoute: typeof ProtectedtenantOrdersIndexRoute
  ProtectedtenantOutletsIndexRoute: typeof ProtectedtenantOutletsIndexRoute
  ProtectedtenantPaymentMethodsIndexRoute: typeof ProtectedtenantPaymentMethodsIndexRoute
  ProtectedtenantPosIndexRoute: typeof ProtectedtenantPosIndexRoute
  ProtectedtenantProductsIndexRoute: typeof ProtectedtenantProductsIndexRoute
  ProtectedtenantSettingsIndexRoute: typeof ProtectedtenantSettingsIndexRoute
  ProtectedtenantStockAdjustmentIndexRoute: typeof ProtectedtenantStockAdjustmentIndexRoute
  ProtectedtenantStocksIndexRoute: typeof ProtectedtenantStocksIndexRoute
  ProtectedtenantUsersIndexRoute: typeof ProtectedtenantUsersIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedtenantDashboardRoute: ProtectedtenantDashboardRoute,
  ProtectedtenantLaporanRoute: ProtectedtenantLaporanRoute,
  ProtectedtenantCashShiftsCashShiftIdRoute:
    ProtectedtenantCashShiftsCashShiftIdRoute,
  ProtectedtenantCategoriesCategoryIdRoute:
    ProtectedtenantCategoriesCategoryIdRoute,
  ProtectedtenantOrdersOrderIdRoute: ProtectedtenantOrdersOrderIdRoute,
  ProtectedtenantOutletsOutletIdRoute: ProtectedtenantOutletsOutletIdRoute,
  ProtectedtenantProductsProductIdRoute: ProtectedtenantProductsProductIdRoute,
  ProtectedtenantProductsNewRoute: ProtectedtenantProductsNewRoute,
  ProtectedglobalAdminIndexRoute: ProtectedglobalAdminIndexRoute,
  ProtectedglobalAllUsersIndexRoute: ProtectedglobalAllUsersIndexRoute,
  ProtectedtenantAccountIndexRoute: ProtectedtenantAccountIndexRoute,
  ProtectedtenantCashShiftsIndexRoute: ProtectedtenantCashShiftsIndexRoute,
  ProtectedtenantCategoriesIndexRoute: ProtectedtenantCategoriesIndexRoute,
  ProtectedtenantDiscountsIndexRoute: ProtectedtenantDiscountsIndexRoute,
  ProtectedtenantOrdersIndexRoute: ProtectedtenantOrdersIndexRoute,
  ProtectedtenantOutletsIndexRoute: ProtectedtenantOutletsIndexRoute,
  ProtectedtenantPaymentMethodsIndexRoute:
    ProtectedtenantPaymentMethodsIndexRoute,
  ProtectedtenantPosIndexRoute: ProtectedtenantPosIndexRoute,
  ProtectedtenantProductsIndexRoute: ProtectedtenantProductsIndexRoute,
  ProtectedtenantSettingsIndexRoute: ProtectedtenantSettingsIndexRoute,
  ProtectedtenantStockAdjustmentIndexRoute:
    ProtectedtenantStockAdjustmentIndexRoute,
  ProtectedtenantStocksIndexRoute: ProtectedtenantStocksIndexRoute,
  ProtectedtenantUsersIndexRoute: ProtectedtenantUsersIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R403Route: R403Route,
  ProtectedRoute: ProtectedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
