/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedTenantsIndexRouteImport } from './routes/_protected/tenants/index'
import { Route as ProtectedTenantsIdRouteImport } from './routes/_protected/tenants/$id'
import { Route as ProtectedInventoryProductRouteImport } from './routes/_protected/inventory/product'
import { Route as ProtectedInventoryOrderRouteImport } from './routes/_protected/inventory/order'
import { Route as ProtectedInventoryNewOrderRouteImport } from './routes/_protected/inventory/new-order'
import { Route as ProtectedInventoryCategoryRouteImport } from './routes/_protected/inventory/category'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedTenantsIndexRoute = ProtectedTenantsIndexRouteImport.update({
  id: '/tenants/',
  path: '/tenants/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedTenantsIdRoute = ProtectedTenantsIdRouteImport.update({
  id: '/tenants/$id',
  path: '/tenants/$id',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedInventoryProductRoute =
  ProtectedInventoryProductRouteImport.update({
    id: '/inventory/product',
    path: '/inventory/product',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedInventoryOrderRoute = ProtectedInventoryOrderRouteImport.update({
  id: '/inventory/order',
  path: '/inventory/order',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedInventoryNewOrderRoute =
  ProtectedInventoryNewOrderRouteImport.update({
    id: '/inventory/new-order',
    path: '/inventory/new-order',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedInventoryCategoryRoute =
  ProtectedInventoryCategoryRouteImport.update({
    id: '/inventory/category',
    path: '/inventory/category',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/inventory/category': typeof ProtectedInventoryCategoryRoute
  '/inventory/new-order': typeof ProtectedInventoryNewOrderRoute
  '/inventory/order': typeof ProtectedInventoryOrderRoute
  '/inventory/product': typeof ProtectedInventoryProductRoute
  '/tenants/$id': typeof ProtectedTenantsIdRoute
  '/tenants/': typeof ProtectedTenantsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/inventory/category': typeof ProtectedInventoryCategoryRoute
  '/inventory/new-order': typeof ProtectedInventoryNewOrderRoute
  '/inventory/order': typeof ProtectedInventoryOrderRoute
  '/inventory/product': typeof ProtectedInventoryProductRoute
  '/tenants/$id': typeof ProtectedTenantsIdRoute
  '/tenants': typeof ProtectedTenantsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/inventory/category': typeof ProtectedInventoryCategoryRoute
  '/_protected/inventory/new-order': typeof ProtectedInventoryNewOrderRoute
  '/_protected/inventory/order': typeof ProtectedInventoryOrderRoute
  '/_protected/inventory/product': typeof ProtectedInventoryProductRoute
  '/_protected/tenants/$id': typeof ProtectedTenantsIdRoute
  '/_protected/tenants/': typeof ProtectedTenantsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/inventory/category'
    | '/inventory/new-order'
    | '/inventory/order'
    | '/inventory/product'
    | '/tenants/$id'
    | '/tenants/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/inventory/category'
    | '/inventory/new-order'
    | '/inventory/order'
    | '/inventory/product'
    | '/tenants/$id'
    | '/tenants'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/login'
    | '/_protected/dashboard'
    | '/_protected/inventory/category'
    | '/_protected/inventory/new-order'
    | '/_protected/inventory/order'
    | '/_protected/inventory/product'
    | '/_protected/tenants/$id'
    | '/_protected/tenants/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/tenants/': {
      id: '/_protected/tenants/'
      path: '/tenants'
      fullPath: '/tenants/'
      preLoaderRoute: typeof ProtectedTenantsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/tenants/$id': {
      id: '/_protected/tenants/$id'
      path: '/tenants/$id'
      fullPath: '/tenants/$id'
      preLoaderRoute: typeof ProtectedTenantsIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/inventory/product': {
      id: '/_protected/inventory/product'
      path: '/inventory/product'
      fullPath: '/inventory/product'
      preLoaderRoute: typeof ProtectedInventoryProductRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/inventory/order': {
      id: '/_protected/inventory/order'
      path: '/inventory/order'
      fullPath: '/inventory/order'
      preLoaderRoute: typeof ProtectedInventoryOrderRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/inventory/new-order': {
      id: '/_protected/inventory/new-order'
      path: '/inventory/new-order'
      fullPath: '/inventory/new-order'
      preLoaderRoute: typeof ProtectedInventoryNewOrderRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/inventory/category': {
      id: '/_protected/inventory/category'
      path: '/inventory/category'
      fullPath: '/inventory/category'
      preLoaderRoute: typeof ProtectedInventoryCategoryRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedInventoryCategoryRoute: typeof ProtectedInventoryCategoryRoute
  ProtectedInventoryNewOrderRoute: typeof ProtectedInventoryNewOrderRoute
  ProtectedInventoryOrderRoute: typeof ProtectedInventoryOrderRoute
  ProtectedInventoryProductRoute: typeof ProtectedInventoryProductRoute
  ProtectedTenantsIdRoute: typeof ProtectedTenantsIdRoute
  ProtectedTenantsIndexRoute: typeof ProtectedTenantsIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedInventoryCategoryRoute: ProtectedInventoryCategoryRoute,
  ProtectedInventoryNewOrderRoute: ProtectedInventoryNewOrderRoute,
  ProtectedInventoryOrderRoute: ProtectedInventoryOrderRoute,
  ProtectedInventoryProductRoute: ProtectedInventoryProductRoute,
  ProtectedTenantsIdRoute: ProtectedTenantsIdRoute,
  ProtectedTenantsIndexRoute: ProtectedTenantsIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
